# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRGbfyC_dZhB0gr1uv9by0XPYHoQZjEM
"""

def step2_umbrella():
    print('Взяла утка-маляр зонтик ☂️, а он ей как раз')

def step2_no_umbrella():
    print('Заходит утка-маляр 🦆 в бар, а там армяне в нарды играют')

def step1():
    print(
        'Утка-маляр 🦆 решила выпить зайти в бар. '
        'Взять ей зонтик? ☂️'
    )
    option = ''
    options = {'да': True, 'нет': False}
    while option not in options:
        print('Выберите: {}/{}'.format(*options))
        option = input()

    if options[option]:
        return step2_umbrella()
    return step2_no_umbrella()


if __name__ == '__main__':
    step1()
